### ISSUE TITLE
Test vagrant file fails to load

### ISSUE THREAD

**Issue by tomjn** [Fred78290/vagrant-multipass#1] opened 2021-05-27 14:19 UTC
I followed the readme instructions, and put the example in an empty folder in a vagrant file and ran `vagrant up --provision`:

```
❯ vagrant up --provision
Bringing machine 'default' up with 'multipass' provider...
==> default: [vagrant-goodhosts] Checking for host entries
/Users/tarendai/.vagrant.d/gems/2.6.7/gems/vagrant-multipass-0.1.0/lib/vagrant-multipass/action/clone.rb:131:in `call': undefined method `exit_code?' for #<Vagrant::Util::Subprocess::Result:0x00007f9ee36e9748> (NoMethodError)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

 - Vagrant 2.2.16
 - MacOS 11.2.3

```
❯ multipass --version
multipass  1.6.2+mac
multipassd 1.6.2+mac
```

The VM is runnning:

```sh
❯ multipass list
Name                    State             IPv4             Image
multipass-test-0        Running           192.168.64.2     Ubuntu 18.04 LTS
multipass-vagrant-test  Running           192.168.64.3     Ubuntu 18.04 LTS
```

I can even SSH into it:

```
❯ multipass shell multipass-vagrant-test
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-143-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu May 27 15:16:07 BST 2021

  System load:  0.12              Processes:             96
  Usage of /:   11.1% of 9.52GB   Users logged in:       0
  Memory usage: 5%                IP address for enp0s2: 192.168.64.3
  Swap usage:   0%




New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@multipass-vagrant-test:~$ ls
ubuntu@multipass-vagrant-test:~$ ls /home
ubuntu  vagrant
ubuntu@multipass-vagrant-test:~$ ls /users
ls: cannot access '/users': No such file or directory
ubuntu@multipass-vagrant-test:~$ ls /
bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  snap  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old
ubuntu@multipass-vagrant-test:~$ exit
logout
```

But `vagrant` is unaware of it, and `/vagrant` does not exist inside the VM

Here's `multipass info` output:

```sh
❯ multipass info multipass-vagrant-test
Name:           multipass-vagrant-test
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 18.04.5 LTS
Image hash:     e834a188b7f1 (Ubuntu 18.04 LTS)
Load:           0.00 0.08 0.06
Disk usage:     1.1G out of 9.5G
Memory usage:   73.4M out of 1.9G
```

**Comment by Fred78290** [comment] 2021-05-27 15:52
Hello, did you run the command vagrant up --provision after already running a vagrant up?

Since I wrote the plug-in, vagrant, ruby, multi pass, MacOS have evolved. so I need to a lot of time to follow evolution 😀

often the problem is vagrant bring it's own outdated ruby environment and pull gems from up to date ruby version.

my latest usage of vagrant was 2.2.9.

regards

**Comment by tomjn** [comment] 2021-05-27 15:58
I've yet to run a `vagrant up` command that succeeds, all instances trigger the stack trace, the first, with `--provision`, without `--provision`, etc

Based on a look at the code, it looks like https://github.com/Fred78290/vagrant-multipass/blob/master/lib/vagrant-multipass/action/clone.rb#L131-L137 should be inside the `begin`/`ensure` block, if the block starts but never reaches the `result = Vagrant::Util::Subprocess.execute(*multipass_cmd)` at the end, then immediately afterward it will try to use `result` which is non-existant

**Comment by tomjn** [comment] 2021-05-27 16:16
The issue is permissions and ownership:

```
~/dev/git/multipassteset/.vagrant/machines/default/multipass 
❯ ls -al
total 16
drwxr-xr-x  4 1000  1000  128 27 May 17:06 .
drwxr-xr-x  3 1000  1000   96 27 May 15:13 ..
-rw-r--r--  1 1000  1000   99 27 May 17:07 box_meta
-rw-r--r--  1 1000  1000   38 27 May 17:06 vagrant_cwd
```

I ran `vagrant up` and got a new error:

```
 INFO interface: Machine: action ["get_state", "start", {:target=>:default}]
 INFO runner: Running action: machine_action_get_state #<Vagrant::Action::Builder:0x00007fb59c9c0c30>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00007fb598b191f8>
 INFO warden: Calling IN action: #<VagrantPlugins::Multipass::Action::GetState:0x00007fb598b19180>
 INFO warden: Calling OUT action: #<VagrantPlugins::Multipass::Action::GetState:0x00007fb598b19180>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00007fb598b191f8>
 INFO interface: Machine: action ["get_state", "end", {:target=>:default}]
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007fb59c958a40>
DEBUG storeboxmetadata: Writing box metadata file to /Users/tarendai/dev/git/multipassteset/.vagrant/machines/default/multipass/box_meta
ERROR warden: Error occurred: Permission denied @ rb_sysopen - /Users/tarendai/dev/git/multipassteset/.vagrant/machines/default/multipass/box_meta
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Permission denied @ rb_sysopen - /Users/tarendai/dev/git/multipassteset/.vagrant/machines/default/multipass/box_meta
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fb598afb7e8>
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-82e881c7f5494529df8da5b5a71f391c
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007fb598b5af90>
/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/up/middleware/store_box_metadata.rb:27:in `initialize': Permission denied @ rb_sysopen - /Users/tarendai/dev/git/multipassteset/.vagrant/machines/default/multipass/box_meta (Errno::EACCES)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/up/middleware/store_box_metadata.rb:27:in `open'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/up/middleware/store_box_metadata.rb:27:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /Users/tarendai/.vagrant.d/gems/2.6.7/gems/vagrant-multipass-0.1.0/lib/vagrant-multipass/action/created.rb:15:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:43:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

For some reason the entire folder has the usser and group `1000`. If I fix that, then run `vagrant up` after ensuring via `multisite list` that there are no instances, I get the original error:

```
❯ vagrant up
Bringing machine 'default' up with 'multipass' provider...
==> default: [vagrant-goodhosts] Checking for host entries
/Users/tarendai/.vagrant.d/gems/2.6.7/gems/vagrant-multipass-0.1.0/lib/vagrant-multipass/action/clone.rb:131:in `call': undefined method `exit_code?' for #<Vagrant::Util::Subprocess::Result:0x00007fca21ad8868> (NoMethodError)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**Comment by tomjn** [comment] 2021-05-27 16:19
I'd also note the `vagrant-cachier` plugin isn't compatible, and I did get an unrelated error for that, but that's to be expected

**Comment by Fred78290** [comment] 2021-05-27 16:21
We must fight many problems at all 😀

so first step is to fix unknown method in clone.rb

**Comment by tomjn** [comment] 2021-05-27 16:38
This is how the virtualbox provider handles execution:

https://github.com/hashicorp/vagrant/blob/main/plugins/providers/virtualbox/driver/base.rb#L387

I'd suggest copying that, but with `multipass` instead of `VBoxManage`

**Comment by Fred78290** [comment] 2021-05-27 16:53
Right, have you the ability to test in local in your environment by editing directly the plugin code in the .vagrant directory and eventually create a PR?

Regards

**Comment by Fred78290** [comment] 2021-05-28 15:35
Hello @tomjn, I have fixed the problem. Could you test again before closing

**Comment by svandragt** [comment] 2021-11-01 10:35
This seems to work, mostly. I can shell into the VM with multipass, but not `vagrant ssh`. the `/vagrant` directory is mapped now.
when running `vagrant up`, the vm is booted but errors at the end, and vagrant isn't aware it's running, but it is, so that's good I guess.

```
vagrant halt
==> multipass-test-0: translation missing: en.vmware_multipass.vm_not_running

vagrant up
...
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 2
ERROR warden: Error occurred: Could not register the VM, mount point fail.
Error: mount failed: source "/home" is not readable

vagrant up --provider multipass     
Bringing machine 'multipass-test-0' up with 'multipass' provider...
==> multipass-test-0: VM already created.
==> multipass-test-0: Powering on VM...
==> multipass-test-0: Waiting for SSH...
==> multipass-test-0: Setting hostname...
==> multipass-test-0: Rsyncing folder: /Users/sander/dev/_thirdparty/vagrant-multipass/ => /vagrant
==> multipass-test-0: Running provisioner: provision for multipass-test-0 (shell)...
    multipass-test-0: Running: inline script
    multipass-test-0: # Your system has configured 'manage_etc_hosts' as True.
    multipass-test-0: # As a result, if you wish for changes to this file to persist
    multipass-test-0: # then you will need to either
    multipass-test-0: # a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
    multipass-test-0: # b.) change or remove the value of 'manage_etc_hosts' in
    multipass-test-0: #     /etc/cloud/cloud.cfg or cloud-config from user-data
    multipass-test-0: #
    multipass-test-0: 127.0.1.1 multipass-test-0 multipass-test-0
    multipass-test-0: 127.0.0.1 localhost
    multipass-test-0: 
    multipass-test-0: # The following lines are desirable for IPv6 capable hosts
    multipass-test-0: ::1 ip6-localhost ip6-loopback
    multipass-test-0: fe00::0 ip6-localnet
    multipass-test-0: ff00::0 ip6-mcastprefix
    multipass-test-0: ff02::1 ip6-allnodes
    multipass-test-0: ff02::2 ip6-allrouters
    multipass-test-0: ff02::3 ip6-allhosts
    multipass-test-0: 
==> multipass-test-0: Running action triggers after up ...
==> multipass-test-0: Running trigger...
==> multipass-test-0: Get IP Address
{:host=>"192.168.6.8", :port=>22, :private_key_path=>["/Users/sander/.ssh/id_rsa"], :keys_only=>true, :verify_host_key=>:never, :username=>"vagrant", :remote_user=>"vagrant", :compression=>true, :dsa_authentication=>true, :extra_args=>nil, :config=>nil, :forward_agent=>false, :forward_x11=>false, :forward_env=>false, :connect_timeout=>15}

vagrant ssh                    
==> multipass-test-0: translation missing: en.vmware_multipass.vm_not_running
```

**Comment by Fred78290** [comment] 2021-11-01 13:34
Hello, could you precise vagrant version, multipass version.

Regards

**Comment by svandragt** [comment] 2021-11-01 13:43
```
$ vagrant --version
Vagrant 2.2.18

$ multipass --version             
multipass   1.8.0+mac
multipassd  1.8.0+mac

macOS 11.6 (20G165)
```

**Comment by Fred78290** [comment] 2021-11-02 10:41
Hello @svandragt 

I have fixed  the problem, now it's working.

Regards

**Closed as completed by Fred78290** 2021-11-02 10:41 UTC
